// src/main/webapp/app/entities/purchase-invoice/purchase-invoice-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IPurchaseInvoice } from 'app/shared/model/purchase-invoice.model';

@Component({
  selector: 'jhi-purchase-invoice-detail',
  templateUrl: './purchase-invoice-detail.component.html',
})
export class PurchaseInvoiceDetailComponent implements OnInit {
  purchaseInvoice: IPurchaseInvoice | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ purchaseInvoice }) => (this.purchaseInvoice = purchaseInvoice));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="purchaseInvoice">
            <h2><span>Purchase Invoice</span> {{ purchaseInvoice.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Supplier Id</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.supplierId }}</span>
                </dd>
                <dt><span>Payment Type</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.paymentType }}</span>
                </dd>
                <dt><span>Purchase Order Id</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.purchaseOrderId }}</span>
                </dd>
                <dt><span>Invoice Status</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.invoiceStatus }}</span>
                </dd>
                <dt><span>Paid Amount</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.paidAmount }}</span>
                </dd>
                <dt><span>Total Amount</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.totalAmount }}</span>
                </dd>
                <dt><span>Tendered Amount</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.tenderedAmount }}</span>
                </dd>
                <dt><span>Discount Availed</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.discountAvailed }}</span>
                </dd>
                <dt><span>Discount Percentage</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.discountPercentage }}</span>
                </dd>
                <dt><span>Discount Amount</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.discountAmount }}</span>
                </dd>
                <dt><span>Created By</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.createdBy }}</span>
                </dd>
                <dt><span>Created Date</span></dt>
                <dd>
                    <span>{{ purchaseInvoice.createdDate }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/purchase-invoice', purchaseInvoice.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/purchase-invoice/purchase-invoice-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './purchase-invoice.reducer';
import { IPurchaseInvoice } from 'app/shared/model/purchase-invoice.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPurchaseInvoiceDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PurchaseInvoiceDetail = (props: IPurchaseInvoiceDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { purchaseInvoiceEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          PurchaseInvoice [<b>{purchaseInvoiceEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="supplierId">Supplier Id</span>
          </dt>
          <dd>{purchaseInvoiceEntity.supplierId}</dd>
          <dt>
            <span id="paymentType">Payment Type</span>
          </dt>
          <dd>{purchaseInvoiceEntity.paymentType}</dd>
          <dt>
            <span id="purchaseOrderId">Purchase Order Id</span>
          </dt>
          <dd>{purchaseInvoiceEntity.purchaseOrderId}</dd>
          <dt>
            <span id="invoiceStatus">Invoice Status</span>
          </dt>
          <dd>{purchaseInvoiceEntity.invoiceStatus}</dd>
          <dt>
            <span id="paidAmount">Paid Amount</span>
          </dt>
          <dd>{purchaseInvoiceEntity.paidAmount}</dd>
          <dt>
            <span id="totalAmount">Total Amount</span>
          </dt>
          <dd>{purchaseInvoiceEntity.totalAmount}</dd>
          <dt>
            <span id="tenderedAmount">Tendered Amount</span>
          </dt>
          <dd>{purchaseInvoiceEntity.tenderedAmount}</dd>
          <dt>
            <span id="discountAvailed">Discount Availed</span>
          </dt>
          <dd>{purchaseInvoiceEntity.discountAvailed ? 'true' : 'false'}</dd>
          <dt>
            <span id="discountPercentage">Discount Percentage</span>
          </dt>
          <dd>{purchaseInvoiceEntity.discountPercentage}</dd>
          <dt>
            <span id="discountAmount">Discount Amount</span>
          </dt>
          <dd>{purchaseInvoiceEntity.discountAmount}</dd>
          <dt>
            <span id="createdBy">Created By</span>
          </dt>
          <dd>{purchaseInvoiceEntity.createdBy}</dd>
          <dt>
            <span id="createdDate">Created Date</span>
          </dt>
          <dd>
            {purchaseInvoiceEntity.createdDate ? (
              <TextFormat value={purchaseInvoiceEntity.createdDate} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
        </dl>
        <Button tag={Link} to="/purchase-invoice" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/purchase-invoice/${purchaseInvoiceEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ purchaseInvoice }: IRootState) => ({
  purchaseInvoiceEntity: purchaseInvoice.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PurchaseInvoiceDetail);
