// src/main/webapp/app/entities/purchase-invoice/purchase-invoice-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './purchase-invoice.reducer';
import { IPurchaseInvoice } from 'app/shared/model/purchase-invoice.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IPurchaseInvoiceUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PurchaseInvoiceUpdate = (props: IPurchaseInvoiceUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { purchaseInvoiceEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/purchase-invoice');
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...purchaseInvoiceEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="posSystemApp.purchaseInvoice.home.createOrEditLabel">Create or edit a PurchaseInvoice</h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : purchaseInvoiceEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="purchase-invoice-id">ID</Label>
                  <AvInput id="purchase-invoice-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="supplierIdLabel" for="purchase-invoice-supplierId">
                  Supplier Id
                </Label>
                <AvField id="purchase-invoice-supplierId" type="string" className="form-control" name="supplierId" />
              </AvGroup>
              <AvGroup>
                <Label id="paymentTypeLabel" for="purchase-invoice-paymentType">
                  Payment Type
                </Label>
                <AvInput
                  id="purchase-invoice-paymentType"
                  type="select"
                  className="form-control"
                  name="paymentType"
                  value={(!isNew && purchaseInvoiceEntity.paymentType) || 'CREDIT'}
                >
                  <option value="CREDIT">CREDIT</option>
                  <option value="CASH">CASH</option>
                  <option value="PARTIAL">PARTIAL</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="purchaseOrderIdLabel" for="purchase-invoice-purchaseOrderId">
                  Purchase Order Id
                </Label>
                <AvField id="purchase-invoice-purchaseOrderId" type="string" className="form-control" name="purchaseOrderId" />
              </AvGroup>
              <AvGroup>
                <Label id="invoiceStatusLabel" for="purchase-invoice-invoiceStatus">
                  Invoice Status
                </Label>
                <AvInput
                  id="purchase-invoice-invoiceStatus"
                  type="select"
                  className="form-control"
                  name="invoiceStatus"
                  value={(!isNew && purchaseInvoiceEntity.invoiceStatus) || 'COMPLETED'}
                >
                  <option value="COMPLETED">COMPLETED</option>
                  <option value="INPROGRESS">INPROGRESS</option>
                  <option value="FAILED">FAILED</option>
                  <option value="CANCELLED">CANCELLED</option>
                  <option value="DELIVERED">DELIVERED</option>
                  <option value="PAYMENT_DUE">PAYMENT_DUE</option>
                  <option value="REFUNDED">REFUNDED</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="paidAmountLabel" for="purchase-invoice-paidAmount">
                  Paid Amount
                </Label>
                <AvField id="purchase-invoice-paidAmount" type="string" className="form-control" name="paidAmount" />
              </AvGroup>
              <AvGroup>
                <Label id="totalAmountLabel" for="purchase-invoice-totalAmount">
                  Total Amount
                </Label>
                <AvField id="purchase-invoice-totalAmount" type="string" className="form-control" name="totalAmount" />
              </AvGroup>
              <AvGroup>
                <Label id="tenderedAmountLabel" for="purchase-invoice-tenderedAmount">
                  Tendered Amount
                </Label>
                <AvField id="purchase-invoice-tenderedAmount" type="string" className="form-control" name="tenderedAmount" />
              </AvGroup>
              <AvGroup check>
                <Label id="discountAvailedLabel">
                  <AvInput id="purchase-invoice-discountAvailed" type="checkbox" className="form-check-input" name="discountAvailed" />
                  Discount Availed
                </Label>
              </AvGroup>
              <AvGroup>
                <Label id="discountPercentageLabel" for="purchase-invoice-discountPercentage">
                  Discount Percentage
                </Label>
                <AvField id="purchase-invoice-discountPercentage" type="string" className="form-control" name="discountPercentage" />
              </AvGroup>
              <AvGroup>
                <Label id="discountAmountLabel" for="purchase-invoice-discountAmount">
                  Discount Amount
                </Label>
                <AvField id="purchase-invoice-discountAmount" type="string" className="form-control" name="discountAmount" />
              </AvGroup>
              <AvGroup>
                <Label id="createdByLabel" for="purchase-invoice-createdBy">
                  Created By
                </Label>
                <AvField id="purchase-invoice-createdBy" type="text" name="createdBy" />
              </AvGroup>
              <AvGroup>
                <Label id="createdDateLabel" for="purchase-invoice-createdDate">
                  Created Date
                </Label>
                <AvField id="purchase-invoice-createdDate" type="date" className="form-control" name="createdDate" />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/purchase-invoice" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  purchaseInvoiceEntity: storeState.purchaseInvoice.entity,
  loading: storeState.purchaseInvoice.loading,
  updating: storeState.purchaseInvoice.updating,
  updateSuccess: storeState.purchaseInvoice.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PurchaseInvoiceUpdate);

// src/main/webapp/app/entities/purchase-invoice/purchase-invoice-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IPurchaseInvoice, PurchaseInvoice } from 'app/shared/model/purchase-invoice.model';
import { PurchaseInvoiceService } from './purchase-invoice.service';

@Component({
  selector: 'jhi-purchase-invoice-update',
  templateUrl: './purchase-invoice-update.component.html',
})
export class PurchaseInvoiceUpdateComponent implements OnInit {
  isSaving = false;
  createdDateDp: any;

  editForm = this.fb.group({
    id: [],
    supplierId: [],
    paymentType: [],
    purchaseOrderId: [],
    invoiceStatus: [],
    paidAmount: [],
    totalAmount: [],
    tenderedAmount: [],
    discountAvailed: [],
    discountPercentage: [],
    discountAmount: [],
    createdBy: [],
    createdDate: [],
  });

  constructor(
    protected purchaseInvoiceService: PurchaseInvoiceService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ purchaseInvoice }) => {
      this.updateForm(purchaseInvoice);
    });
  }

  updateForm(purchaseInvoice: IPurchaseInvoice): void {
    this.editForm.patchValue({
      id: purchaseInvoice.id,
      supplierId: purchaseInvoice.supplierId,
      paymentType: purchaseInvoice.paymentType,
      purchaseOrderId: purchaseInvoice.purchaseOrderId,
      invoiceStatus: purchaseInvoice.invoiceStatus,
      paidAmount: purchaseInvoice.paidAmount,
      totalAmount: purchaseInvoice.totalAmount,
      tenderedAmount: purchaseInvoice.tenderedAmount,
      discountAvailed: purchaseInvoice.discountAvailed,
      discountPercentage: purchaseInvoice.discountPercentage,
      discountAmount: purchaseInvoice.discountAmount,
      createdBy: purchaseInvoice.createdBy,
      createdDate: purchaseInvoice.createdDate,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const purchaseInvoice = this.createFromForm();
    if (purchaseInvoice.id !== undefined) {
      this.subscribeToSaveResponse(this.purchaseInvoiceService.update(purchaseInvoice));
    } else {
      this.subscribeToSaveResponse(this.purchaseInvoiceService.create(purchaseInvoice));
    }
  }

  private createFromForm(): IPurchaseInvoice {
    return {
      ...new PurchaseInvoice(),
      id: this.editForm.get(['id'])!.value,
      supplierId: this.editForm.get(['supplierId'])!.value,
      paymentType: this.editForm.get(['paymentType'])!.value,
      purchaseOrderId: this.editForm.get(['purchaseOrderId'])!.value,
      invoiceStatus: this.editForm.get(['invoiceStatus'])!.value,
      paidAmount: this.editForm.get(['paidAmount'])!.value,
      totalAmount: this.editForm.get(['totalAmount'])!.value,
      tenderedAmount: this.editForm.get(['tenderedAmount'])!.value,
      discountAvailed: this.editForm.get(['discountAvailed'])!.value,
      discountPercentage: this.editForm.get(['discountPercentage'])!.value,
      discountAmount: this.editForm.get(['discountAmount'])!.value,
      createdBy: this.editForm.get(['createdBy'])!.value,
      createdDate: this.editForm.get(['createdDate'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IPurchaseInvoice>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-purchase-invoice-heading">Create or edit a Purchase Invoice</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_supplierId">Supplier Id</label>
                    <input type="number" class="form-control" name="supplierId" id="field_supplierId"
                           formControlName="supplierId"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_paymentType">Payment Type</label>
                    <select class="form-control" name="paymentType" formControlName="paymentType" id="field_paymentType">
                        <option value="CREDIT">CREDIT</option>
                        <option value="CASH">CASH</option>
                        <option value="PARTIAL">PARTIAL</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_purchaseOrderId">Purchase Order Id</label>
                    <input type="number" class="form-control" name="purchaseOrderId" id="field_purchaseOrderId"
                           formControlName="purchaseOrderId"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_invoiceStatus">Invoice Status</label>
                    <select class="form-control" name="invoiceStatus" formControlName="invoiceStatus" id="field_invoiceStatus">
                        <option value="COMPLETED">COMPLETED</option>
                        <option value="INPROGRESS">INPROGRESS</option>
                        <option value="FAILED">FAILED</option>
                        <option value="CANCELLED">CANCELLED</option>
                        <option value="DELIVERED">DELIVERED</option>
                        <option value="PAYMENT_DUE">PAYMENT_DUE</option>
                        <option value="REFUNDED">REFUNDED</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_paidAmount">Paid Amount</label>
                    <input type="number" class="form-control" name="paidAmount" id="field_paidAmount"
                           formControlName="paidAmount"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_totalAmount">Total Amount</label>
                    <input type="number" class="form-control" name="totalAmount" id="field_totalAmount"
                           formControlName="totalAmount"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_tenderedAmount">Tendered Amount</label>
                    <input type="number" class="form-control" name="tenderedAmount" id="field_tenderedAmount"
                           formControlName="tenderedAmount"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_discountAvailed">Discount Availed</label>
                    <input type="checkbox" class="form-control" name="discountAvailed" id="field_discountAvailed"
                           formControlName="discountAvailed"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_discountPercentage">Discount Percentage</label>
                    <input type="number" class="form-control" name="discountPercentage" id="field_discountPercentage"
                           formControlName="discountPercentage"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_discountAmount">Discount Amount</label>
                    <input type="number" class="form-control" name="discountAmount" id="field_discountAmount"
                           formControlName="discountAmount"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_createdBy">Created By</label>
                    <input type="text" class="form-control" name="createdBy" id="field_createdBy"
                           formControlName="createdBy"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_createdDate">Created Date</label>
                    <div class="input-group">
                        <input id="field_createdDate" type="text" class="form-control" name="createdDate" ngbDatepicker #createdDateDp="ngbDatepicker" formControlName="createdDate"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="createdDateDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
