// src/main/webapp/app/entities/purchase-invoice/purchase-invoice.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './purchase-invoice.reducer';
import { IPurchaseInvoice } from 'app/shared/model/purchase-invoice.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPurchaseInvoiceProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const PurchaseInvoice = (props: IPurchaseInvoiceProps) => {
  useEffect(() => {
    props.getEntities();
  }, []);

  const { purchaseInvoiceList, match, loading } = props;
  return (
    <div>
      <h2 id="purchase-invoice-heading">
        Purchase Invoices
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Purchase Invoice
        </Link>
      </h2>
      <div className="table-responsive">
        {purchaseInvoiceList && purchaseInvoiceList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th>Supplier Id</th>
                <th>Payment Type</th>
                <th>Purchase Order Id</th>
                <th>Invoice Status</th>
                <th>Paid Amount</th>
                <th>Total Amount</th>
                <th>Tendered Amount</th>
                <th>Discount Availed</th>
                <th>Discount Percentage</th>
                <th>Discount Amount</th>
                <th>Created By</th>
                <th>Created Date</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {purchaseInvoiceList.map((purchaseInvoice, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${purchaseInvoice.id}`} color="link" size="sm">
                      {purchaseInvoice.id}
                    </Button>
                  </td>
                  <td>{purchaseInvoice.supplierId}</td>
                  <td>{purchaseInvoice.paymentType}</td>
                  <td>{purchaseInvoice.purchaseOrderId}</td>
                  <td>{purchaseInvoice.invoiceStatus}</td>
                  <td>{purchaseInvoice.paidAmount}</td>
                  <td>{purchaseInvoice.totalAmount}</td>
                  <td>{purchaseInvoice.tenderedAmount}</td>
                  <td>{purchaseInvoice.discountAvailed ? 'true' : 'false'}</td>
                  <td>{purchaseInvoice.discountPercentage}</td>
                  <td>{purchaseInvoice.discountAmount}</td>
                  <td>{purchaseInvoice.createdBy}</td>
                  <td>
                    {purchaseInvoice.createdDate ? (
                      <TextFormat type="date" value={purchaseInvoice.createdDate} format={APP_LOCAL_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${purchaseInvoice.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${purchaseInvoice.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${purchaseInvoice.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Purchase Invoices found</div>
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ purchaseInvoice }: IRootState) => ({
  purchaseInvoiceList: purchaseInvoice.entities,
  loading: purchaseInvoice.loading,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PurchaseInvoice);

// src/main/webapp/app/entities/purchase-invoice/purchase-invoice.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPurchaseInvoice } from 'app/shared/model/purchase-invoice.model';
import { PurchaseInvoiceService } from './purchase-invoice.service';
import { PurchaseInvoiceDeleteDialogComponent } from './purchase-invoice-delete-dialog.component';

@Component({
  selector: 'jhi-purchase-invoice',
  templateUrl: './purchase-invoice.component.html',
})
export class PurchaseInvoiceComponent implements OnInit, OnDestroy {
  purchaseInvoices?: IPurchaseInvoice[];
  eventSubscriber?: Subscription;

  constructor(
    protected purchaseInvoiceService: PurchaseInvoiceService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadAll(): void {
    this.purchaseInvoiceService.query().subscribe((res: HttpResponse<IPurchaseInvoice[]>) => (this.purchaseInvoices = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInPurchaseInvoices();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IPurchaseInvoice): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInPurchaseInvoices(): void {
    this.eventSubscriber = this.eventManager.subscribe('purchaseInvoiceListModification', () => this.loadAll());
  }

  delete(purchaseInvoice: IPurchaseInvoice): void {
    const modalRef = this.modalService.open(PurchaseInvoiceDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.purchaseInvoice = purchaseInvoice;
  }
}

<div>
    <h2 id="page-heading">
        <span>Purchase Invoices</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-purchase-invoice" [routerLink]="['/purchase-invoice/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Purchase Invoice
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="purchaseInvoices?.length === 0">
        <span>No purchaseInvoices found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="purchaseInvoices && purchaseInvoices.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span>ID</span></th>
                    <th scope="col" ><span>Supplier Id</span></th>
                    <th scope="col" ><span>Payment Type</span></th>
                    <th scope="col" ><span>Purchase Order Id</span></th>
                    <th scope="col" ><span>Invoice Status</span></th>
                    <th scope="col" ><span>Paid Amount</span></th>
                    <th scope="col" ><span>Total Amount</span></th>
                    <th scope="col" ><span>Tendered Amount</span></th>
                    <th scope="col" ><span>Discount Availed</span></th>
                    <th scope="col" ><span>Discount Percentage</span></th>
                    <th scope="col" ><span>Discount Amount</span></th>
                    <th scope="col" ><span>Created By</span></th>
                    <th scope="col" ><span>Created Date</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let purchaseInvoice of purchaseInvoices ;trackBy: trackId">
                    <td><a [routerLink]="['/purchase-invoice', purchaseInvoice.id, 'view']">{{ purchaseInvoice.id }}</a></td>
                    <td>{{ purchaseInvoice.supplierId }}</td>
                    <td>{{ purchaseInvoice.paymentType }}</td>
                    <td>{{ purchaseInvoice.purchaseOrderId }}</td>
                    <td>{{ purchaseInvoice.invoiceStatus }}</td>
                    <td>{{ purchaseInvoice.paidAmount }}</td>
                    <td>{{ purchaseInvoice.totalAmount }}</td>
                    <td>{{ purchaseInvoice.tenderedAmount }}</td>
                    <td>{{ purchaseInvoice.discountAvailed }}</td>
                    <td>{{ purchaseInvoice.discountPercentage }}</td>
                    <td>{{ purchaseInvoice.discountAmount }}</td>
                    <td>{{ purchaseInvoice.createdBy }}</td>
                    <td>{{ purchaseInvoice.createdDate | date:'mediumDate' }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/purchase-invoice', purchaseInvoice.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/purchase-invoice', purchaseInvoice.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(purchaseInvoice)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
