// src/main/webapp/app/entities/supplier/supplier.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ISupplier } from 'app/shared/model/supplier.model';
import { SupplierService } from './supplier.service';
import { SupplierDeleteDialogComponent } from './supplier-delete-dialog.component';

@Component({
  selector: 'jhi-supplier',
  templateUrl: './supplier.component.html',
})
export class SupplierComponent implements OnInit, OnDestroy {
  suppliers?: ISupplier[];
  eventSubscriber?: Subscription;

  constructor(protected supplierService: SupplierService, protected eventManager: JhiEventManager, protected modalService: NgbModal) {}

  loadAll(): void {
    this.supplierService.query().subscribe((res: HttpResponse<ISupplier[]>) => (this.suppliers = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInSuppliers();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: ISupplier): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInSuppliers(): void {
    this.eventSubscriber = this.eventManager.subscribe('supplierListModification', () => this.loadAll());
  }

  delete(supplier: ISupplier): void {
    const modalRef = this.modalService.open(SupplierDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.supplier = supplier;
  }
}

<div>
    <h2 id="page-heading">
        <span>Suppliers</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-supplier" [routerLink]="['/supplier/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Supplier
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="suppliers?.length === 0">
        <span>No suppliers found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="suppliers && suppliers.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span>ID</span></th>
                    <th scope="col" ><span>Name</span></th>
                    <th scope="col" ><span>Address</span></th>
                    <th scope="col" ><span>Contact No</span></th>
                    <th scope="col" ><span>Contact Person</span></th>
                    <th scope="col" ><span>Contact Person No</span></th>
                    <th scope="col" ><span>Created By</span></th>
                    <th scope="col" ><span>Created Date</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let supplier of suppliers ;trackBy: trackId">
                    <td><a [routerLink]="['/supplier', supplier.id, 'view']">{{ supplier.id }}</a></td>
                    <td>{{ supplier.name }}</td>
                    <td>{{ supplier.address }}</td>
                    <td>{{ supplier.contactNo }}</td>
                    <td>{{ supplier.contactPerson }}</td>
                    <td>{{ supplier.contactPersonNo }}</td>
                    <td>{{ supplier.createdBy }}</td>
                    <td>{{ supplier.createdDate | date:'mediumDate' }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/supplier', supplier.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/supplier', supplier.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(supplier)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/supplier/supplier.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './supplier.reducer';
import { ISupplier } from 'app/shared/model/supplier.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ISupplierProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Supplier = (props: ISupplierProps) => {
  useEffect(() => {
    props.getEntities();
  }, []);

  const { supplierList, match, loading } = props;
  return (
    <div>
      <h2 id="supplier-heading">
        Suppliers
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Supplier
        </Link>
      </h2>
      <div className="table-responsive">
        {supplierList && supplierList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Address</th>
                <th>Contact No</th>
                <th>Contact Person</th>
                <th>Contact Person No</th>
                <th>Created By</th>
                <th>Created Date</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {supplierList.map((supplier, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${supplier.id}`} color="link" size="sm">
                      {supplier.id}
                    </Button>
                  </td>
                  <td>{supplier.name}</td>
                  <td>{supplier.address}</td>
                  <td>{supplier.contactNo}</td>
                  <td>{supplier.contactPerson}</td>
                  <td>{supplier.contactPersonNo}</td>
                  <td>{supplier.createdBy}</td>
                  <td>
                    {supplier.createdDate ? <TextFormat type="date" value={supplier.createdDate} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${supplier.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${supplier.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${supplier.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Suppliers found</div>
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ supplier }: IRootState) => ({
  supplierList: supplier.entities,
  loading: supplier.loading,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Supplier);
