// src/main/webapp/app/entities/purchase-order-breakdown/purchase-order-breakdown-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './purchase-order-breakdown.reducer';
import { IPurchaseOrderBreakdown } from 'app/shared/model/purchase-order-breakdown.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPurchaseOrderBreakdownDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PurchaseOrderBreakdownDetail = (props: IPurchaseOrderBreakdownDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { purchaseOrderBreakdownEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          PurchaseOrderBreakdown [<b>{purchaseOrderBreakdownEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="purchaseOrderId">Purchase Order Id</span>
          </dt>
          <dd>{purchaseOrderBreakdownEntity.purchaseOrderId}</dd>
          <dt>
            <span id="productId">Product Id</span>
          </dt>
          <dd>{purchaseOrderBreakdownEntity.productId}</dd>
          <dt>
            <span id="quantity">Quantity</span>
          </dt>
          <dd>{purchaseOrderBreakdownEntity.quantity}</dd>
          <dt>
            <span id="unitPrice">Unit Price</span>
          </dt>
          <dd>{purchaseOrderBreakdownEntity.unitPrice}</dd>
        </dl>
        <Button tag={Link} to="/purchase-order-breakdown" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/purchase-order-breakdown/${purchaseOrderBreakdownEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ purchaseOrderBreakdown }: IRootState) => ({
  purchaseOrderBreakdownEntity: purchaseOrderBreakdown.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PurchaseOrderBreakdownDetail);

// src/main/webapp/app/entities/purchase-order-breakdown/purchase-order-breakdown-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IPurchaseOrderBreakdown } from 'app/shared/model/purchase-order-breakdown.model';

@Component({
  selector: 'jhi-purchase-order-breakdown-detail',
  templateUrl: './purchase-order-breakdown-detail.component.html',
})
export class PurchaseOrderBreakdownDetailComponent implements OnInit {
  purchaseOrderBreakdown: IPurchaseOrderBreakdown | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ purchaseOrderBreakdown }) => (this.purchaseOrderBreakdown = purchaseOrderBreakdown));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="purchaseOrderBreakdown">
            <h2><span>Purchase Order Breakdown</span> {{ purchaseOrderBreakdown.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Purchase Order Id</span></dt>
                <dd>
                    <span>{{ purchaseOrderBreakdown.purchaseOrderId }}</span>
                </dd>
                <dt><span>Product Id</span></dt>
                <dd>
                    <span>{{ purchaseOrderBreakdown.productId }}</span>
                </dd>
                <dt><span>Quantity</span></dt>
                <dd>
                    <span>{{ purchaseOrderBreakdown.quantity }}</span>
                </dd>
                <dt><span>Unit Price</span></dt>
                <dd>
                    <span>{{ purchaseOrderBreakdown.unitPrice }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/purchase-order-breakdown', purchaseOrderBreakdown.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>
