// src/main/webapp/app/entities/purchase-order-breakdown/purchase-order-breakdown.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './purchase-order-breakdown.reducer';
import { IPurchaseOrderBreakdown } from 'app/shared/model/purchase-order-breakdown.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPurchaseOrderBreakdownProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const PurchaseOrderBreakdown = (props: IPurchaseOrderBreakdownProps) => {
  useEffect(() => {
    props.getEntities();
  }, []);

  const { purchaseOrderBreakdownList, match, loading } = props;
  return (
    <div>
      <h2 id="purchase-order-breakdown-heading">
        Purchase Order Breakdowns
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Purchase Order Breakdown
        </Link>
      </h2>
      <div className="table-responsive">
        {purchaseOrderBreakdownList && purchaseOrderBreakdownList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th>Purchase Order Id</th>
                <th>Product Id</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {purchaseOrderBreakdownList.map((purchaseOrderBreakdown, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${purchaseOrderBreakdown.id}`} color="link" size="sm">
                      {purchaseOrderBreakdown.id}
                    </Button>
                  </td>
                  <td>{purchaseOrderBreakdown.purchaseOrderId}</td>
                  <td>{purchaseOrderBreakdown.productId}</td>
                  <td>{purchaseOrderBreakdown.quantity}</td>
                  <td>{purchaseOrderBreakdown.unitPrice}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${purchaseOrderBreakdown.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${purchaseOrderBreakdown.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${purchaseOrderBreakdown.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Purchase Order Breakdowns found</div>
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ purchaseOrderBreakdown }: IRootState) => ({
  purchaseOrderBreakdownList: purchaseOrderBreakdown.entities,
  loading: purchaseOrderBreakdown.loading,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PurchaseOrderBreakdown);

// src/main/webapp/app/entities/purchase-order-breakdown/purchase-order-breakdown.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPurchaseOrderBreakdown } from 'app/shared/model/purchase-order-breakdown.model';
import { PurchaseOrderBreakdownService } from './purchase-order-breakdown.service';
import { PurchaseOrderBreakdownDeleteDialogComponent } from './purchase-order-breakdown-delete-dialog.component';

@Component({
  selector: 'jhi-purchase-order-breakdown',
  templateUrl: './purchase-order-breakdown.component.html',
})
export class PurchaseOrderBreakdownComponent implements OnInit, OnDestroy {
  purchaseOrderBreakdowns?: IPurchaseOrderBreakdown[];
  eventSubscriber?: Subscription;

  constructor(
    protected purchaseOrderBreakdownService: PurchaseOrderBreakdownService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadAll(): void {
    this.purchaseOrderBreakdownService
      .query()
      .subscribe((res: HttpResponse<IPurchaseOrderBreakdown[]>) => (this.purchaseOrderBreakdowns = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInPurchaseOrderBreakdowns();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IPurchaseOrderBreakdown): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInPurchaseOrderBreakdowns(): void {
    this.eventSubscriber = this.eventManager.subscribe('purchaseOrderBreakdownListModification', () => this.loadAll());
  }

  delete(purchaseOrderBreakdown: IPurchaseOrderBreakdown): void {
    const modalRef = this.modalService.open(PurchaseOrderBreakdownDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.purchaseOrderBreakdown = purchaseOrderBreakdown;
  }
}

<div>
    <h2 id="page-heading">
        <span>Purchase Order Breakdowns</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-purchase-order-breakdown" [routerLink]="['/purchase-order-breakdown/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Purchase Order Breakdown
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="purchaseOrderBreakdowns?.length === 0">
        <span>No purchaseOrderBreakdowns found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="purchaseOrderBreakdowns && purchaseOrderBreakdowns.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span>ID</span></th>
                    <th scope="col" ><span>Purchase Order Id</span></th>
                    <th scope="col" ><span>Product Id</span></th>
                    <th scope="col" ><span>Quantity</span></th>
                    <th scope="col" ><span>Unit Price</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let purchaseOrderBreakdown of purchaseOrderBreakdowns ;trackBy: trackId">
                    <td><a [routerLink]="['/purchase-order-breakdown', purchaseOrderBreakdown.id, 'view']">{{ purchaseOrderBreakdown.id }}</a></td>
                    <td>{{ purchaseOrderBreakdown.purchaseOrderId }}</td>
                    <td>{{ purchaseOrderBreakdown.productId }}</td>
                    <td>{{ purchaseOrderBreakdown.quantity }}</td>
                    <td>{{ purchaseOrderBreakdown.unitPrice }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/purchase-order-breakdown', purchaseOrderBreakdown.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/purchase-order-breakdown', purchaseOrderBreakdown.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(purchaseOrderBreakdown)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
