// src/main/webapp/app/entities/product-company/product-company-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './product-company.reducer';
import { IProductCompany } from 'app/shared/model/product-company.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IProductCompanyDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ProductCompanyDetail = (props: IProductCompanyDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { productCompanyEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          ProductCompany [<b>{productCompanyEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="name">Name</span>
          </dt>
          <dd>{productCompanyEntity.name}</dd>
          <dt>
            <span id="address">Address</span>
          </dt>
          <dd>{productCompanyEntity.address}</dd>
          <dt>
            <span id="contactNo">Contact No</span>
          </dt>
          <dd>{productCompanyEntity.contactNo}</dd>
          <dt>
            <span id="contactPerson">Contact Person</span>
          </dt>
          <dd>{productCompanyEntity.contactPerson}</dd>
          <dt>
            <span id="contactPersonNo">Contact Person No</span>
          </dt>
          <dd>{productCompanyEntity.contactPersonNo}</dd>
          <dt>
            <span id="createdBy">Created By</span>
          </dt>
          <dd>{productCompanyEntity.createdBy}</dd>
          <dt>
            <span id="createdDate">Created Date</span>
          </dt>
          <dd>
            {productCompanyEntity.createdDate ? (
              <TextFormat value={productCompanyEntity.createdDate} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
        </dl>
        <Button tag={Link} to="/product-company" replace color="info">
          <FontAwesomeIcon icon="arrow-left" /> <span className="d-none d-md-inline">Back</span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/product-company/${productCompanyEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ productCompany }: IRootState) => ({
  productCompanyEntity: productCompany.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ProductCompanyDetail);

// src/main/webapp/app/entities/product-company/product-company-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IProductCompany } from 'app/shared/model/product-company.model';

@Component({
  selector: 'jhi-product-company-detail',
  templateUrl: './product-company-detail.component.html',
})
export class ProductCompanyDetailComponent implements OnInit {
  productCompany: IProductCompany | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ productCompany }) => (this.productCompany = productCompany));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="productCompany">
            <h2><span>Product Company</span> {{ productCompany.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span>Name</span></dt>
                <dd>
                    <span>{{ productCompany.name }}</span>
                </dd>
                <dt><span>Address</span></dt>
                <dd>
                    <span>{{ productCompany.address }}</span>
                </dd>
                <dt><span>Contact No</span></dt>
                <dd>
                    <span>{{ productCompany.contactNo }}</span>
                </dd>
                <dt><span>Contact Person</span></dt>
                <dd>
                    <span>{{ productCompany.contactPerson }}</span>
                </dd>
                <dt><span>Contact Person No</span></dt>
                <dd>
                    <span>{{ productCompany.contactPersonNo }}</span>
                </dd>
                <dt><span>Created By</span></dt>
                <dd>
                    <span>{{ productCompany.createdBy }}</span>
                </dd>
                <dt><span>Created Date</span></dt>
                <dd>
                    <span>{{ productCompany.createdDate }}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/product-company', productCompany.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
            </button>
        </div>
    </div>
</div>
