// src/main/webapp/app/entities/product-company/product-company.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IProductCompany } from 'app/shared/model/product-company.model';
import { ProductCompanyService } from './product-company.service';
import { ProductCompanyDeleteDialogComponent } from './product-company-delete-dialog.component';

@Component({
  selector: 'jhi-product-company',
  templateUrl: './product-company.component.html',
})
export class ProductCompanyComponent implements OnInit, OnDestroy {
  productCompanies?: IProductCompany[];
  eventSubscriber?: Subscription;

  constructor(
    protected productCompanyService: ProductCompanyService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadAll(): void {
    this.productCompanyService.query().subscribe((res: HttpResponse<IProductCompany[]>) => (this.productCompanies = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInProductCompanies();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IProductCompany): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInProductCompanies(): void {
    this.eventSubscriber = this.eventManager.subscribe('productCompanyListModification', () => this.loadAll());
  }

  delete(productCompany: IProductCompany): void {
    const modalRef = this.modalService.open(ProductCompanyDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.productCompany = productCompany;
  }
}

<div>
    <h2 id="page-heading">
        <span>Product Companies</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-product-company" [routerLink]="['/product-company/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Product Company
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="productCompanies?.length === 0">
        <span>No productCompanies found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="productCompanies && productCompanies.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span>ID</span></th>
                    <th scope="col" ><span>Name</span></th>
                    <th scope="col" ><span>Address</span></th>
                    <th scope="col" ><span>Contact No</span></th>
                    <th scope="col" ><span>Contact Person</span></th>
                    <th scope="col" ><span>Contact Person No</span></th>
                    <th scope="col" ><span>Created By</span></th>
                    <th scope="col" ><span>Created Date</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let productCompany of productCompanies ;trackBy: trackId">
                    <td><a [routerLink]="['/product-company', productCompany.id, 'view']">{{ productCompany.id }}</a></td>
                    <td>{{ productCompany.name }}</td>
                    <td>{{ productCompany.address }}</td>
                    <td>{{ productCompany.contactNo }}</td>
                    <td>{{ productCompany.contactPerson }}</td>
                    <td>{{ productCompany.contactPersonNo }}</td>
                    <td>{{ productCompany.createdBy }}</td>
                    <td>{{ productCompany.createdDate | date:'mediumDate' }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/product-company', productCompany.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/product-company', productCompany.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(productCompany)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/product-company/product-company.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './product-company.reducer';
import { IProductCompany } from 'app/shared/model/product-company.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IProductCompanyProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const ProductCompany = (props: IProductCompanyProps) => {
  useEffect(() => {
    props.getEntities();
  }, []);

  const { productCompanyList, match, loading } = props;
  return (
    <div>
      <h2 id="product-company-heading">
        Product Companies
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Product Company
        </Link>
      </h2>
      <div className="table-responsive">
        {productCompanyList && productCompanyList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Address</th>
                <th>Contact No</th>
                <th>Contact Person</th>
                <th>Contact Person No</th>
                <th>Created By</th>
                <th>Created Date</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {productCompanyList.map((productCompany, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${productCompany.id}`} color="link" size="sm">
                      {productCompany.id}
                    </Button>
                  </td>
                  <td>{productCompany.name}</td>
                  <td>{productCompany.address}</td>
                  <td>{productCompany.contactNo}</td>
                  <td>{productCompany.contactPerson}</td>
                  <td>{productCompany.contactPersonNo}</td>
                  <td>{productCompany.createdBy}</td>
                  <td>
                    {productCompany.createdDate ? (
                      <TextFormat type="date" value={productCompany.createdDate} format={APP_LOCAL_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${productCompany.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${productCompany.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${productCompany.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Product Companies found</div>
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ productCompany }: IRootState) => ({
  productCompanyList: productCompany.entities,
  loading: productCompany.loading,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ProductCompany);
