// src/main/webapp/app/entities/store-product/store-product.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { ICrudGetAllAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './store-product.reducer';
import { IStoreProduct } from 'app/shared/model/store-product.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IStoreProductProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const StoreProduct = (props: IStoreProductProps) => {
  useEffect(() => {
    props.getEntities();
  }, []);

  const { storeProductList, match, loading } = props;
  return (
    <div>
      <h2 id="store-product-heading">
        Store Products
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp; Create new Store Product
        </Link>
      </h2>
      <div className="table-responsive">
        {storeProductList && storeProductList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th>Product Id</th>
                <th>Store Id</th>
                <th>Quantity</th>
                <th>Created By</th>
                <th>Created Date</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {storeProductList.map((storeProduct, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${storeProduct.id}`} color="link" size="sm">
                      {storeProduct.id}
                    </Button>
                  </td>
                  <td>{storeProduct.productId}</td>
                  <td>{storeProduct.storeId}</td>
                  <td>{storeProduct.quantity}</td>
                  <td>{storeProduct.createdBy}</td>
                  <td>
                    {storeProduct.createdDate ? (
                      <TextFormat type="date" value={storeProduct.createdDate} format={APP_LOCAL_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${storeProduct.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${storeProduct.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${storeProduct.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Store Products found</div>
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ storeProduct }: IRootState) => ({
  storeProductList: storeProduct.entities,
  loading: storeProduct.loading,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(StoreProduct);

// src/main/webapp/app/entities/store-product/store-product.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IStoreProduct } from 'app/shared/model/store-product.model';
import { StoreProductService } from './store-product.service';
import { StoreProductDeleteDialogComponent } from './store-product-delete-dialog.component';

@Component({
  selector: 'jhi-store-product',
  templateUrl: './store-product.component.html',
})
export class StoreProductComponent implements OnInit, OnDestroy {
  storeProducts?: IStoreProduct[];
  eventSubscriber?: Subscription;

  constructor(
    protected storeProductService: StoreProductService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadAll(): void {
    this.storeProductService.query().subscribe((res: HttpResponse<IStoreProduct[]>) => (this.storeProducts = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInStoreProducts();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IStoreProduct): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInStoreProducts(): void {
    this.eventSubscriber = this.eventManager.subscribe('storeProductListModification', () => this.loadAll());
  }

  delete(storeProduct: IStoreProduct): void {
    const modalRef = this.modalService.open(StoreProductDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.storeProduct = storeProduct;
  }
}

<div>
    <h2 id="page-heading">
        <span>Store Products</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-store-product" [routerLink]="['/store-product/new']">
            <fa-icon icon="plus"></fa-icon>
            <span>
            Create a new Store Product
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="storeProducts?.length === 0">
        <span>No storeProducts found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="storeProducts && storeProducts.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span>ID</span></th>
                    <th scope="col" ><span>Product Id</span></th>
                    <th scope="col" ><span>Store Id</span></th>
                    <th scope="col" ><span>Quantity</span></th>
                    <th scope="col" ><span>Created By</span></th>
                    <th scope="col" ><span>Created Date</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let storeProduct of storeProducts ;trackBy: trackId">
                    <td><a [routerLink]="['/store-product', storeProduct.id, 'view']">{{ storeProduct.id }}</a></td>
                    <td>{{ storeProduct.productId }}</td>
                    <td>{{ storeProduct.storeId }}</td>
                    <td>{{ storeProduct.quantity }}</td>
                    <td>{{ storeProduct.createdBy }}</td>
                    <td>{{ storeProduct.createdDate | date:'mediumDate' }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/store-product', storeProduct.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/store-product', storeProduct.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(storeProduct)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
