// src/main/webapp/app/entities/purchase-order/purchase-order-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IPurchaseOrder, PurchaseOrder } from 'app/shared/model/purchase-order.model';
import { PurchaseOrderService } from './purchase-order.service';

@Component({
  selector: 'jhi-purchase-order-update',
  templateUrl: './purchase-order-update.component.html',
})
export class PurchaseOrderUpdateComponent implements OnInit {
  isSaving = false;
  shippingDateDp: any;
  createdDateDp: any;

  editForm = this.fb.group({
    id: [],
    supplierId: [],
    totalAmount: [],
    paymentType: [],
    orderStatus: [],
    paymentStatus: [],
    shippingDate: [],
    shippingRequired: [null, [Validators.required]],
    createdDate: [],
    createdBy: [],
    remarks: [],
  });

  constructor(protected purchaseOrderService: PurchaseOrderService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ purchaseOrder }) => {
      this.updateForm(purchaseOrder);
    });
  }

  updateForm(purchaseOrder: IPurchaseOrder): void {
    this.editForm.patchValue({
      id: purchaseOrder.id,
      supplierId: purchaseOrder.supplierId,
      totalAmount: purchaseOrder.totalAmount,
      paymentType: purchaseOrder.paymentType,
      orderStatus: purchaseOrder.orderStatus,
      paymentStatus: purchaseOrder.paymentStatus,
      shippingDate: purchaseOrder.shippingDate,
      shippingRequired: purchaseOrder.shippingRequired,
      createdDate: purchaseOrder.createdDate,
      createdBy: purchaseOrder.createdBy,
      remarks: purchaseOrder.remarks,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const purchaseOrder = this.createFromForm();
    if (purchaseOrder.id !== undefined) {
      this.subscribeToSaveResponse(this.purchaseOrderService.update(purchaseOrder));
    } else {
      this.subscribeToSaveResponse(this.purchaseOrderService.create(purchaseOrder));
    }
  }

  private createFromForm(): IPurchaseOrder {
    return {
      ...new PurchaseOrder(),
      id: this.editForm.get(['id'])!.value,
      supplierId: this.editForm.get(['supplierId'])!.value,
      totalAmount: this.editForm.get(['totalAmount'])!.value,
      paymentType: this.editForm.get(['paymentType'])!.value,
      orderStatus: this.editForm.get(['orderStatus'])!.value,
      paymentStatus: this.editForm.get(['paymentStatus'])!.value,
      shippingDate: this.editForm.get(['shippingDate'])!.value,
      shippingRequired: this.editForm.get(['shippingRequired'])!.value,
      createdDate: this.editForm.get(['createdDate'])!.value,
      createdBy: this.editForm.get(['createdBy'])!.value,
      remarks: this.editForm.get(['remarks'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IPurchaseOrder>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-purchase-order-heading">Create or edit a Purchase Order</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_supplierId">Supplier Id</label>
                    <input type="number" class="form-control" name="supplierId" id="field_supplierId"
                           formControlName="supplierId"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_totalAmount">Total Amount</label>
                    <input type="number" class="form-control" name="totalAmount" id="field_totalAmount"
                           formControlName="totalAmount"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_paymentType">Payment Type</label>
                    <select class="form-control" name="paymentType" formControlName="paymentType" id="field_paymentType">
                        <option value="CREDIT">CREDIT</option>
                        <option value="CASH">CASH</option>
                        <option value="PARTIAL">PARTIAL</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_orderStatus">Order Status</label>
                    <select class="form-control" name="orderStatus" formControlName="orderStatus" id="field_orderStatus">
                        <option value="COMPLETED">COMPLETED</option>
                        <option value="INPROGRESS">INPROGRESS</option>
                        <option value="FAILED">FAILED</option>
                        <option value="CANCELLED">CANCELLED</option>
                        <option value="DELIVERED">DELIVERED</option>
                        <option value="PAYMENT_DUE">PAYMENT_DUE</option>
                        <option value="REFUNDED">REFUNDED</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_paymentStatus">Payment Status</label>
                    <select class="form-control" name="paymentStatus" formControlName="paymentStatus" id="field_paymentStatus">
                        <option value="PAID">PAID</option>
                        <option value="UNPAID">UNPAID</option>
                        <option value="PARTIAL_PAID">PARTIAL_PAID</option>
                        <option value="REFUNDED">REFUNDED</option>
                        <option value="PARTIAL_REFUNDED">PARTIAL_REFUNDED</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_shippingDate">Shipping Date</label>
                    <div class="input-group">
                        <input id="field_shippingDate" type="text" class="form-control" name="shippingDate" ngbDatepicker #shippingDateDp="ngbDatepicker" formControlName="shippingDate"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="shippingDateDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_shippingRequired">Shipping Required</label>
                    <input type="checkbox" class="form-control" name="shippingRequired" id="field_shippingRequired"
                           formControlName="shippingRequired"/>
                    <div *ngIf="editForm.get('shippingRequired')!.invalid && (editForm.get('shippingRequired')!.dirty || editForm.get('shippingRequired')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('shippingRequired')?.errors?.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_createdDate">Created Date</label>
                    <div class="input-group">
                        <input id="field_createdDate" type="text" class="form-control" name="createdDate" ngbDatepicker #createdDateDp="ngbDatepicker" formControlName="createdDate"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="createdDateDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_createdBy">Created By</label>
                    <input type="text" class="form-control" name="createdBy" id="field_createdBy"
                           formControlName="createdBy"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" for="field_remarks">Remarks</label>
                    <input type="text" class="form-control" name="remarks" id="field_remarks"
                           formControlName="remarks"/>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/purchase-order/purchase-order-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './purchase-order.reducer';
import { IPurchaseOrder } from 'app/shared/model/purchase-order.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IPurchaseOrderUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PurchaseOrderUpdate = (props: IPurchaseOrderUpdateProps) => {
  const [isNew, setIsNew] = useState(!props.match.params || !props.match.params.id);

  const { purchaseOrderEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/purchase-order' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...purchaseOrderEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="posSystemApp.purchaseOrder.home.createOrEditLabel">Create or edit a PurchaseOrder</h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : purchaseOrderEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="purchase-order-id">ID</Label>
                  <AvInput id="purchase-order-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="supplierIdLabel" for="purchase-order-supplierId">
                  Supplier Id
                </Label>
                <AvField id="purchase-order-supplierId" type="string" className="form-control" name="supplierId" />
              </AvGroup>
              <AvGroup>
                <Label id="totalAmountLabel" for="purchase-order-totalAmount">
                  Total Amount
                </Label>
                <AvField id="purchase-order-totalAmount" type="string" className="form-control" name="totalAmount" />
              </AvGroup>
              <AvGroup>
                <Label id="paymentTypeLabel" for="purchase-order-paymentType">
                  Payment Type
                </Label>
                <AvInput
                  id="purchase-order-paymentType"
                  type="select"
                  className="form-control"
                  name="paymentType"
                  value={(!isNew && purchaseOrderEntity.paymentType) || 'CREDIT'}
                >
                  <option value="CREDIT">CREDIT</option>
                  <option value="CASH">CASH</option>
                  <option value="PARTIAL">PARTIAL</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="orderStatusLabel" for="purchase-order-orderStatus">
                  Order Status
                </Label>
                <AvInput
                  id="purchase-order-orderStatus"
                  type="select"
                  className="form-control"
                  name="orderStatus"
                  value={(!isNew && purchaseOrderEntity.orderStatus) || 'COMPLETED'}
                >
                  <option value="COMPLETED">COMPLETED</option>
                  <option value="INPROGRESS">INPROGRESS</option>
                  <option value="FAILED">FAILED</option>
                  <option value="CANCELLED">CANCELLED</option>
                  <option value="DELIVERED">DELIVERED</option>
                  <option value="PAYMENT_DUE">PAYMENT_DUE</option>
                  <option value="REFUNDED">REFUNDED</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="paymentStatusLabel" for="purchase-order-paymentStatus">
                  Payment Status
                </Label>
                <AvInput
                  id="purchase-order-paymentStatus"
                  type="select"
                  className="form-control"
                  name="paymentStatus"
                  value={(!isNew && purchaseOrderEntity.paymentStatus) || 'PAID'}
                >
                  <option value="PAID">PAID</option>
                  <option value="UNPAID">UNPAID</option>
                  <option value="PARTIAL_PAID">PARTIAL_PAID</option>
                  <option value="REFUNDED">REFUNDED</option>
                  <option value="PARTIAL_REFUNDED">PARTIAL_REFUNDED</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="shippingDateLabel" for="purchase-order-shippingDate">
                  Shipping Date
                </Label>
                <AvField id="purchase-order-shippingDate" type="date" className="form-control" name="shippingDate" />
              </AvGroup>
              <AvGroup check>
                <Label id="shippingRequiredLabel">
                  <AvInput id="purchase-order-shippingRequired" type="checkbox" className="form-check-input" name="shippingRequired" />
                  Shipping Required
                </Label>
              </AvGroup>
              <AvGroup>
                <Label id="createdDateLabel" for="purchase-order-createdDate">
                  Created Date
                </Label>
                <AvField id="purchase-order-createdDate" type="date" className="form-control" name="createdDate" />
              </AvGroup>
              <AvGroup>
                <Label id="createdByLabel" for="purchase-order-createdBy">
                  Created By
                </Label>
                <AvField id="purchase-order-createdBy" type="text" name="createdBy" />
              </AvGroup>
              <AvGroup>
                <Label id="remarksLabel" for="purchase-order-remarks">
                  Remarks
                </Label>
                <AvField id="purchase-order-remarks" type="text" name="remarks" />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/purchase-order" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  purchaseOrderEntity: storeState.purchaseOrder.entity,
  loading: storeState.purchaseOrder.loading,
  updating: storeState.purchaseOrder.updating,
  updateSuccess: storeState.purchaseOrder.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PurchaseOrderUpdate);
